#!/usr/bin/env bash
# vim:ft=sh:ts=4:sw=4:noet
#
# Install PostQF sources and create a launcher script.

set -euo pipefail
declare -r BNAME="$(basename ${0})"

function _die {
	echo >&2 "$@"
	exit 1
}

function _install {
	local tarball="${RELEASE}.tar.gz"
	local url="https://github.com/rseichter/postqf/archive/refs/tags/${tarball}"
	local t="$(mktemp)"
	trap "rm ${t}" EXIT
	curl -f -L -o ${t} ${url} || _die "Failed to download ${url}"
	tar xzf ${t} --no-same-owner

	cat >postqf <<EOT
#!/usr/bin/env bash
#
# PostQF launcher script. Python code was downloaded on $(date -I) from
# ${url}

PYTHONPATH="$(realpath postqf-${RELEASE})" python3 -m postqf \$*
EOT
	chmod +x postqf
	echo You can now launch PostQF using $(realpath postqf)
}

if [ $# -eq 0 ]; then
	RELEASE="0.2"
elif [ $# -eq 1 ]; then
	RELEASE="${1}"
else
	_die "Usage: ${BNAME} [release]"
fi
_install
