# vim:ft=yaml:ts=2:sw=2:et

name: Python build and code tests
on:
  push:
    branches-ignore:
      - docs*

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: make -C tests coverage

      - name: Build distribution
        run: make dist

      - name: Upload source code
        uses: actions/upload-artifact@v2
        with:
          name: postqf-source
          path: dist/*.gz

      - name: Upload wheel package
        uses: actions/upload-artifact@v2
        with:
          name: postqf-wheel
          path: dist/*.whl
