# vim:ft=yaml:ts=2:sw=2:et

name: PostQF project jobs
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Python build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: make -C tests coverage

      - name: Build distribution
        run: make dist

      - name: Upload Python artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-artifacts
          path: dist/*

  publish-pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Python artifacts
        uses: actions/download-artifact@v2

      - name: Prepare dist directory
        run: mv python-artifacts dist

      - name: Publish to PyPI test repository
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_TESTREPO }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
